#!/bin/bash

mkdir -p Output_LocalSearch
mkdir -p Output_SpecificLocalSearch
mkdir -p Output_CplexAndLocalSearch

make Clean
make

echo "********************* Recherche Locale *********************"
for instance in GAP/GAP-*.dat
do
    echo "Recherche de l'instance" $instance
    output=${instance/GAP/Output_LocalSearch}
    ./Bin/MonExec ${instance} LocalSearch > ${output}
done
echo
echo "***** Recherche locale depuis une bonne solution Cplex *****"
for instance in GAP/GAP-*.dat
do
    echo "Recherche de l'instance" $instance
    output=${instance/GAP/Output_CplexAndLocalSearch}
    ./Bin/MonExec ${instance} SpecificLocalSearch > ${output}
done
echo
echo "****************** Generation de colonnes ******************"
for instance in GAP/GAP-*.dat
do
    echo "Recherche de l'instance" $instance
    output=${instance/GAP/Output_ColumnGeneration}
    ./Bin/MonExec ${instance} ColumnGen > ${output}
done
